dist:
- amd64

language: java

script:
  - mvn clean package

deploy:
  - provider: releases
  - api_key: ${API_KEY}
  - file_glob: true
  - file: target/*.jar
  - skip_cleanup: true
  - on:
      - tags: true